# usb
CONFIG_ZMK_USB=y

# sensor
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y   

# battery
CONFIG_ZMK_BATTERY_REPORTING=y
CONFIG_ZMK_BATTERY_REPORT_INTERVAL=30

CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y

# behaviors
CONFIG_ZMK_BEHAVIORS_QUEUE_SIZE=512
CONFIG_INPUT_QUEUE_MAX_MSGS=64

# bluetooth
CONFIG_BT=y
CONFIG_ZMK_BLE=y
CONFIG_BT_CTLR_PHY_2M=n
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y
# 增加发射功率
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# soft off
CONFIG_ZMK_PM_SOFT_OFF=y

# mouse
CONFIG_ZMK_MOUSE=y

# zmk studio
CONFIG_ZMK_STUDIO=y

# stack size
CONFIG_MAIN_STACK_SIZE=8192
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=8192
CONFIG_HEAP_MEM_POOL_SIZE=16384

# logging
CONFIG_ZMK_LOG_LEVEL_DBG=y
CONFIG_INPUT_LOG_LEVEL_DBG=y
CONFIG_LOG_PROCESS_THREAD_STARTUP_DELAY_MS=8000

# sleep
CONFIG_ZMK_SLEEP=n





